// 代码内置违禁词（fallback）。优先使用数据库 blocked_words 表，
// 表内容为空或读取失败时回落到此列表。
export const BLOCKED_WORDS_FALLBACK: { word: string; category: string }[] = [
  { word: '高仿', category: 'fake' },
  { word: '仿牌', category: 'fake' },
  { word: '复刻', category: 'fake' },
  { word: 'A货', category: 'fake' },
  { word: '1:1', category: 'fake' },
  { word: '盗版', category: 'piracy' },
  { word: '破解版', category: 'piracy' },
  { word: '香烟', category: 'tobacco' },
  { word: '烟丝', category: 'tobacco' },
  { word: '烟弹', category: 'ecig' },
  { word: '电子烟', category: 'ecig' },
  { word: 'vape', category: 'ecig' },
  { word: 'juul', category: 'ecig' },
  { word: '大麻', category: 'drug' },
  { word: 'CBD', category: 'drug' },
  { word: 'THC', category: 'drug' },
  { word: '毒品', category: 'drug' },
  { word: '摇头丸', category: 'drug' },
  { word: '枪支', category: 'weapon' },
  { word: '弹药', category: 'weapon' },
  { word: '弹簧刀', category: 'weapon' },
  { word: '辣椒喷雾', category: 'weapon' },
  { word: '防身喷雾', category: 'weapon' },
  { word: '色情', category: 'porn' },
  { word: '援交', category: 'porn' },
  { word: '赌博', category: 'gambling' },
  { word: '博彩', category: 'gambling' },
  { word: '假证', category: 'fake_id' },
  { word: '假驾照', category: 'fake_id' },
  { word: '假身份证', category: 'fake_id' },
  { word: '自制食品', category: 'food' },
  { word: '自制蛋糕', category: 'food' },
  { word: '贷款', category: 'finance' },
  { word: '高利贷', category: 'finance' },
  { word: '投资理财', category: 'finance' },
  { word: '不问出处', category: 'stolen' },
]
